version: "3.8"
services:

  db:
    build: ./docker/db
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

  app:
    build: ./docker/app
    depends_on:
      - db
    networks:
      - backend
      - frontend
    volumes:
      - ./src:/code
      - ./storage/:/app/storage
    tty: true
    env_file:
      - .env
    ports:
      - "18081:8000"
    entrypoint: python manage.py runserver 0.0.0.0:8000

volumes:
  db-data:

networks:
  backend:
  frontend:
